// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginMessages.proto

package com.server.Protobufs;

public final class LoginMessages {
  private LoginMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MsgState}
   */
  public enum MsgState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MS_ERROR = 0;</code>
     */
    MS_ERROR(0),
    /**
     * <code>MS_INIT = 1;</code>
     */
    MS_INIT(1),
    /**
     * <code>MS_SUCCESSFUL = 2;</code>
     */
    MS_SUCCESSFUL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MS_ERROR = 0;</code>
     */
    public static final int MS_ERROR_VALUE = 0;
    /**
     * <code>MS_INIT = 1;</code>
     */
    public static final int MS_INIT_VALUE = 1;
    /**
     * <code>MS_SUCCESSFUL = 2;</code>
     */
    public static final int MS_SUCCESSFUL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MsgState forNumber(int value) {
      switch (value) {
        case 0: return MS_ERROR;
        case 1: return MS_INIT;
        case 2: return MS_SUCCESSFUL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgState>() {
            public MsgState findValueByNumber(int number) {
              return MsgState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.server.Protobufs.LoginMessages.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgState[] VALUES = values();

    public static MsgState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MsgState)
  }

  public interface CheckRegParameterStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CheckRegParameterStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string login = 1;</code>
     * @return Whether the login field is set.
     */
    boolean hasLogin();
    /**
     * <code>string login = 1;</code>
     * @return The login.
     */
    java.lang.String getLogin();
    /**
     * <code>string login = 1;</code>
     * @return The bytes for login.
     */
    com.google.protobuf.ByteString
        getLoginBytes();

    /**
     * <code>string mail = 2;</code>
     * @return Whether the mail field is set.
     */
    boolean hasMail();
    /**
     * <code>string mail = 2;</code>
     * @return The mail.
     */
    java.lang.String getMail();
    /**
     * <code>string mail = 2;</code>
     * @return The bytes for mail.
     */
    com.google.protobuf.ByteString
        getMailBytes();

    /**
     * <code>bool loginStatus = 3;</code>
     * @return Whether the loginStatus field is set.
     */
    boolean hasLoginStatus();
    /**
     * <code>bool loginStatus = 3;</code>
     * @return The loginStatus.
     */
    boolean getLoginStatus();

    /**
     * <code>bool mailStatus = 4;</code>
     * @return Whether the mailStatus field is set.
     */
    boolean hasMailStatus();
    /**
     * <code>bool mailStatus = 4;</code>
     * @return The mailStatus.
     */
    boolean getMailStatus();

    public com.server.Protobufs.LoginMessages.CheckRegParameterStatus.V1Case getV1Case();
  }
  /**
   * Protobuf type {@code CheckRegParameterStatus}
   */
  public static final class CheckRegParameterStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CheckRegParameterStatus)
      CheckRegParameterStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CheckRegParameterStatus.newBuilder() to construct.
    private CheckRegParameterStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckRegParameterStatus() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CheckRegParameterStatus();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CheckRegParameterStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              v1Case_ = 1;
              v1_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              v1Case_ = 2;
              v1_ = s;
              break;
            }
            case 24: {
              v1_ = input.readBool();
              v1Case_ = 3;
              break;
            }
            case 32: {
              v1_ = input.readBool();
              v1Case_ = 4;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.Protobufs.LoginMessages.internal_static_CheckRegParameterStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.Protobufs.LoginMessages.internal_static_CheckRegParameterStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.Protobufs.LoginMessages.CheckRegParameterStatus.class, com.server.Protobufs.LoginMessages.CheckRegParameterStatus.Builder.class);
    }

    private int v1Case_ = 0;
    private java.lang.Object v1_;
    public enum V1Case
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      LOGIN(1),
      MAIL(2),
      LOGINSTATUS(3),
      MAILSTATUS(4),
      V1_NOT_SET(0);
      private final int value;
      private V1Case(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static V1Case valueOf(int value) {
        return forNumber(value);
      }

      public static V1Case forNumber(int value) {
        switch (value) {
          case 1: return LOGIN;
          case 2: return MAIL;
          case 3: return LOGINSTATUS;
          case 4: return MAILSTATUS;
          case 0: return V1_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public V1Case
    getV1Case() {
      return V1Case.forNumber(
          v1Case_);
    }

    public static final int LOGIN_FIELD_NUMBER = 1;
    /**
     * <code>string login = 1;</code>
     * @return Whether the login field is set.
     */
    public boolean hasLogin() {
      return v1Case_ == 1;
    }
    /**
     * <code>string login = 1;</code>
     * @return The login.
     */
    public java.lang.String getLogin() {
      java.lang.Object ref = "";
      if (v1Case_ == 1) {
        ref = v1_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (v1Case_ == 1) {
          v1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string login = 1;</code>
     * @return The bytes for login.
     */
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = "";
      if (v1Case_ == 1) {
        ref = v1_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (v1Case_ == 1) {
          v1_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAIL_FIELD_NUMBER = 2;
    /**
     * <code>string mail = 2;</code>
     * @return Whether the mail field is set.
     */
    public boolean hasMail() {
      return v1Case_ == 2;
    }
    /**
     * <code>string mail = 2;</code>
     * @return The mail.
     */
    public java.lang.String getMail() {
      java.lang.Object ref = "";
      if (v1Case_ == 2) {
        ref = v1_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (v1Case_ == 2) {
          v1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string mail = 2;</code>
     * @return The bytes for mail.
     */
    public com.google.protobuf.ByteString
        getMailBytes() {
      java.lang.Object ref = "";
      if (v1Case_ == 2) {
        ref = v1_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (v1Case_ == 2) {
          v1_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGINSTATUS_FIELD_NUMBER = 3;
    /**
     * <code>bool loginStatus = 3;</code>
     * @return Whether the loginStatus field is set.
     */
    @java.lang.Override
    public boolean hasLoginStatus() {
      return v1Case_ == 3;
    }
    /**
     * <code>bool loginStatus = 3;</code>
     * @return The loginStatus.
     */
    @java.lang.Override
    public boolean getLoginStatus() {
      if (v1Case_ == 3) {
        return (java.lang.Boolean) v1_;
      }
      return false;
    }

    public static final int MAILSTATUS_FIELD_NUMBER = 4;
    /**
     * <code>bool mailStatus = 4;</code>
     * @return Whether the mailStatus field is set.
     */
    @java.lang.Override
    public boolean hasMailStatus() {
      return v1Case_ == 4;
    }
    /**
     * <code>bool mailStatus = 4;</code>
     * @return The mailStatus.
     */
    @java.lang.Override
    public boolean getMailStatus() {
      if (v1Case_ == 4) {
        return (java.lang.Boolean) v1_;
      }
      return false;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (v1Case_ == 1) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, v1_);
      }
      if (v1Case_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, v1_);
      }
      if (v1Case_ == 3) {
        output.writeBool(
            3, (boolean)((java.lang.Boolean) v1_));
      }
      if (v1Case_ == 4) {
        output.writeBool(
            4, (boolean)((java.lang.Boolean) v1_));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (v1Case_ == 1) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, v1_);
      }
      if (v1Case_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, v1_);
      }
      if (v1Case_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              3, (boolean)((java.lang.Boolean) v1_));
      }
      if (v1Case_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              4, (boolean)((java.lang.Boolean) v1_));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.server.Protobufs.LoginMessages.CheckRegParameterStatus)) {
        return super.equals(obj);
      }
      com.server.Protobufs.LoginMessages.CheckRegParameterStatus other = (com.server.Protobufs.LoginMessages.CheckRegParameterStatus) obj;

      if (!getV1Case().equals(other.getV1Case())) return false;
      switch (v1Case_) {
        case 1:
          if (!getLogin()
              .equals(other.getLogin())) return false;
          break;
        case 2:
          if (!getMail()
              .equals(other.getMail())) return false;
          break;
        case 3:
          if (getLoginStatus()
              != other.getLoginStatus()) return false;
          break;
        case 4:
          if (getMailStatus()
              != other.getMailStatus()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (v1Case_) {
        case 1:
          hash = (37 * hash) + LOGIN_FIELD_NUMBER;
          hash = (53 * hash) + getLogin().hashCode();
          break;
        case 2:
          hash = (37 * hash) + MAIL_FIELD_NUMBER;
          hash = (53 * hash) + getMail().hashCode();
          break;
        case 3:
          hash = (37 * hash) + LOGINSTATUS_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getLoginStatus());
          break;
        case 4:
          hash = (37 * hash) + MAILSTATUS_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getMailStatus());
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.server.Protobufs.LoginMessages.CheckRegParameterStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.Protobufs.LoginMessages.CheckRegParameterStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.CheckRegParameterStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.Protobufs.LoginMessages.CheckRegParameterStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.CheckRegParameterStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.Protobufs.LoginMessages.CheckRegParameterStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.CheckRegParameterStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.server.Protobufs.LoginMessages.CheckRegParameterStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.CheckRegParameterStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.server.Protobufs.LoginMessages.CheckRegParameterStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.CheckRegParameterStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.server.Protobufs.LoginMessages.CheckRegParameterStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.server.Protobufs.LoginMessages.CheckRegParameterStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CheckRegParameterStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CheckRegParameterStatus)
        com.server.Protobufs.LoginMessages.CheckRegParameterStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.Protobufs.LoginMessages.internal_static_CheckRegParameterStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.Protobufs.LoginMessages.internal_static_CheckRegParameterStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.Protobufs.LoginMessages.CheckRegParameterStatus.class, com.server.Protobufs.LoginMessages.CheckRegParameterStatus.Builder.class);
      }

      // Construct using com.server.Protobufs.LoginMessages.CheckRegParameterStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        v1Case_ = 0;
        v1_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.server.Protobufs.LoginMessages.internal_static_CheckRegParameterStatus_descriptor;
      }

      @java.lang.Override
      public com.server.Protobufs.LoginMessages.CheckRegParameterStatus getDefaultInstanceForType() {
        return com.server.Protobufs.LoginMessages.CheckRegParameterStatus.getDefaultInstance();
      }

      @java.lang.Override
      public com.server.Protobufs.LoginMessages.CheckRegParameterStatus build() {
        com.server.Protobufs.LoginMessages.CheckRegParameterStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.server.Protobufs.LoginMessages.CheckRegParameterStatus buildPartial() {
        com.server.Protobufs.LoginMessages.CheckRegParameterStatus result = new com.server.Protobufs.LoginMessages.CheckRegParameterStatus(this);
        if (v1Case_ == 1) {
          result.v1_ = v1_;
        }
        if (v1Case_ == 2) {
          result.v1_ = v1_;
        }
        if (v1Case_ == 3) {
          result.v1_ = v1_;
        }
        if (v1Case_ == 4) {
          result.v1_ = v1_;
        }
        result.v1Case_ = v1Case_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.server.Protobufs.LoginMessages.CheckRegParameterStatus) {
          return mergeFrom((com.server.Protobufs.LoginMessages.CheckRegParameterStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.server.Protobufs.LoginMessages.CheckRegParameterStatus other) {
        if (other == com.server.Protobufs.LoginMessages.CheckRegParameterStatus.getDefaultInstance()) return this;
        switch (other.getV1Case()) {
          case LOGIN: {
            v1Case_ = 1;
            v1_ = other.v1_;
            onChanged();
            break;
          }
          case MAIL: {
            v1Case_ = 2;
            v1_ = other.v1_;
            onChanged();
            break;
          }
          case LOGINSTATUS: {
            setLoginStatus(other.getLoginStatus());
            break;
          }
          case MAILSTATUS: {
            setMailStatus(other.getMailStatus());
            break;
          }
          case V1_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.server.Protobufs.LoginMessages.CheckRegParameterStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.server.Protobufs.LoginMessages.CheckRegParameterStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int v1Case_ = 0;
      private java.lang.Object v1_;
      public V1Case
          getV1Case() {
        return V1Case.forNumber(
            v1Case_);
      }

      public Builder clearV1() {
        v1Case_ = 0;
        v1_ = null;
        onChanged();
        return this;
      }


      /**
       * <code>string login = 1;</code>
       * @return Whether the login field is set.
       */
      @java.lang.Override
      public boolean hasLogin() {
        return v1Case_ == 1;
      }
      /**
       * <code>string login = 1;</code>
       * @return The login.
       */
      @java.lang.Override
      public java.lang.String getLogin() {
        java.lang.Object ref = "";
        if (v1Case_ == 1) {
          ref = v1_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (v1Case_ == 1) {
            v1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string login = 1;</code>
       * @return The bytes for login.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLoginBytes() {
        java.lang.Object ref = "";
        if (v1Case_ == 1) {
          ref = v1_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (v1Case_ == 1) {
            v1_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string login = 1;</code>
       * @param value The login to set.
       * @return This builder for chaining.
       */
      public Builder setLogin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  v1Case_ = 1;
        v1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string login = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogin() {
        if (v1Case_ == 1) {
          v1Case_ = 0;
          v1_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string login = 1;</code>
       * @param value The bytes for login to set.
       * @return This builder for chaining.
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        v1Case_ = 1;
        v1_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string mail = 2;</code>
       * @return Whether the mail field is set.
       */
      @java.lang.Override
      public boolean hasMail() {
        return v1Case_ == 2;
      }
      /**
       * <code>string mail = 2;</code>
       * @return The mail.
       */
      @java.lang.Override
      public java.lang.String getMail() {
        java.lang.Object ref = "";
        if (v1Case_ == 2) {
          ref = v1_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (v1Case_ == 2) {
            v1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mail = 2;</code>
       * @return The bytes for mail.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMailBytes() {
        java.lang.Object ref = "";
        if (v1Case_ == 2) {
          ref = v1_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (v1Case_ == 2) {
            v1_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mail = 2;</code>
       * @param value The mail to set.
       * @return This builder for chaining.
       */
      public Builder setMail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  v1Case_ = 2;
        v1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mail = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMail() {
        if (v1Case_ == 2) {
          v1Case_ = 0;
          v1_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string mail = 2;</code>
       * @param value The bytes for mail to set.
       * @return This builder for chaining.
       */
      public Builder setMailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        v1Case_ = 2;
        v1_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bool loginStatus = 3;</code>
       * @return Whether the loginStatus field is set.
       */
      public boolean hasLoginStatus() {
        return v1Case_ == 3;
      }
      /**
       * <code>bool loginStatus = 3;</code>
       * @return The loginStatus.
       */
      public boolean getLoginStatus() {
        if (v1Case_ == 3) {
          return (java.lang.Boolean) v1_;
        }
        return false;
      }
      /**
       * <code>bool loginStatus = 3;</code>
       * @param value The loginStatus to set.
       * @return This builder for chaining.
       */
      public Builder setLoginStatus(boolean value) {
        v1Case_ = 3;
        v1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool loginStatus = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoginStatus() {
        if (v1Case_ == 3) {
          v1Case_ = 0;
          v1_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>bool mailStatus = 4;</code>
       * @return Whether the mailStatus field is set.
       */
      public boolean hasMailStatus() {
        return v1Case_ == 4;
      }
      /**
       * <code>bool mailStatus = 4;</code>
       * @return The mailStatus.
       */
      public boolean getMailStatus() {
        if (v1Case_ == 4) {
          return (java.lang.Boolean) v1_;
        }
        return false;
      }
      /**
       * <code>bool mailStatus = 4;</code>
       * @param value The mailStatus to set.
       * @return This builder for chaining.
       */
      public Builder setMailStatus(boolean value) {
        v1Case_ = 4;
        v1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool mailStatus = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMailStatus() {
        if (v1Case_ == 4) {
          v1Case_ = 0;
          v1_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CheckRegParameterStatus)
    }

    // @@protoc_insertion_point(class_scope:CheckRegParameterStatus)
    private static final com.server.Protobufs.LoginMessages.CheckRegParameterStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.server.Protobufs.LoginMessages.CheckRegParameterStatus();
    }

    public static com.server.Protobufs.LoginMessages.CheckRegParameterStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckRegParameterStatus>
        PARSER = new com.google.protobuf.AbstractParser<CheckRegParameterStatus>() {
      @java.lang.Override
      public CheckRegParameterStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CheckRegParameterStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CheckRegParameterStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckRegParameterStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.server.Protobufs.LoginMessages.CheckRegParameterStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Login)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mail = 1;</code>
     * @return The mail.
     */
    java.lang.String getMail();
    /**
     * <code>string mail = 1;</code>
     * @return The bytes for mail.
     */
    com.google.protobuf.ByteString
        getMailBytes();

    /**
     * <code>string hash = 2;</code>
     * @return The hash.
     */
    java.lang.String getHash();
    /**
     * <code>string hash = 2;</code>
     * @return The bytes for hash.
     */
    com.google.protobuf.ByteString
        getHashBytes();

    /**
     * <code>.MsgState state = 3;</code>
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();
    /**
     * <code>.MsgState state = 3;</code>
     * @return The state.
     */
    com.server.Protobufs.LoginMessages.MsgState getState();
  }
  /**
   * Protobuf type {@code Login}
   */
  public static final class Login extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Login)
      LoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Login.newBuilder() to construct.
    private Login(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Login() {
      mail_ = "";
      hash_ = "";
      state_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Login();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              mail_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              hash_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.Protobufs.LoginMessages.internal_static_Login_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.Protobufs.LoginMessages.internal_static_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.Protobufs.LoginMessages.Login.class, com.server.Protobufs.LoginMessages.Login.Builder.class);
    }

    public static final int MAIL_FIELD_NUMBER = 1;
    private volatile java.lang.Object mail_;
    /**
     * <code>string mail = 1;</code>
     * @return The mail.
     */
    @java.lang.Override
    public java.lang.String getMail() {
      java.lang.Object ref = mail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mail_ = s;
        return s;
      }
    }
    /**
     * <code>string mail = 1;</code>
     * @return The bytes for mail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMailBytes() {
      java.lang.Object ref = mail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HASH_FIELD_NUMBER = 2;
    private volatile java.lang.Object hash_;
    /**
     * <code>string hash = 2;</code>
     * @return The hash.
     */
    @java.lang.Override
    public java.lang.String getHash() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hash_ = s;
        return s;
      }
    }
    /**
     * <code>string hash = 2;</code>
     * @return The bytes for hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHashBytes() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 3;
    private int state_;
    /**
     * <code>.MsgState state = 3;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.MsgState state = 3;</code>
     * @return The state.
     */
    @java.lang.Override public com.server.Protobufs.LoginMessages.MsgState getState() {
      @SuppressWarnings("deprecation")
      com.server.Protobufs.LoginMessages.MsgState result = com.server.Protobufs.LoginMessages.MsgState.valueOf(state_);
      return result == null ? com.server.Protobufs.LoginMessages.MsgState.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mail_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mail_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hash_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hash_);
      }
      if (state_ != com.server.Protobufs.LoginMessages.MsgState.MS_ERROR.getNumber()) {
        output.writeEnum(3, state_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mail_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mail_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hash_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hash_);
      }
      if (state_ != com.server.Protobufs.LoginMessages.MsgState.MS_ERROR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.server.Protobufs.LoginMessages.Login)) {
        return super.equals(obj);
      }
      com.server.Protobufs.LoginMessages.Login other = (com.server.Protobufs.LoginMessages.Login) obj;

      if (!getMail()
          .equals(other.getMail())) return false;
      if (!getHash()
          .equals(other.getHash())) return false;
      if (state_ != other.state_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAIL_FIELD_NUMBER;
      hash = (53 * hash) + getMail().hashCode();
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.server.Protobufs.LoginMessages.Login parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.Protobufs.LoginMessages.Login parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.Protobufs.LoginMessages.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.Protobufs.LoginMessages.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.server.Protobufs.LoginMessages.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.server.Protobufs.LoginMessages.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.server.Protobufs.LoginMessages.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.server.Protobufs.LoginMessages.Login prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Login)
        com.server.Protobufs.LoginMessages.LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.Protobufs.LoginMessages.internal_static_Login_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.Protobufs.LoginMessages.internal_static_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.Protobufs.LoginMessages.Login.class, com.server.Protobufs.LoginMessages.Login.Builder.class);
      }

      // Construct using com.server.Protobufs.LoginMessages.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mail_ = "";

        hash_ = "";

        state_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.server.Protobufs.LoginMessages.internal_static_Login_descriptor;
      }

      @java.lang.Override
      public com.server.Protobufs.LoginMessages.Login getDefaultInstanceForType() {
        return com.server.Protobufs.LoginMessages.Login.getDefaultInstance();
      }

      @java.lang.Override
      public com.server.Protobufs.LoginMessages.Login build() {
        com.server.Protobufs.LoginMessages.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.server.Protobufs.LoginMessages.Login buildPartial() {
        com.server.Protobufs.LoginMessages.Login result = new com.server.Protobufs.LoginMessages.Login(this);
        result.mail_ = mail_;
        result.hash_ = hash_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.server.Protobufs.LoginMessages.Login) {
          return mergeFrom((com.server.Protobufs.LoginMessages.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.server.Protobufs.LoginMessages.Login other) {
        if (other == com.server.Protobufs.LoginMessages.Login.getDefaultInstance()) return this;
        if (!other.getMail().isEmpty()) {
          mail_ = other.mail_;
          onChanged();
        }
        if (!other.getHash().isEmpty()) {
          hash_ = other.hash_;
          onChanged();
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.server.Protobufs.LoginMessages.Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.server.Protobufs.LoginMessages.Login) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object mail_ = "";
      /**
       * <code>string mail = 1;</code>
       * @return The mail.
       */
      public java.lang.String getMail() {
        java.lang.Object ref = mail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mail = 1;</code>
       * @return The bytes for mail.
       */
      public com.google.protobuf.ByteString
          getMailBytes() {
        java.lang.Object ref = mail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mail = 1;</code>
       * @param value The mail to set.
       * @return This builder for chaining.
       */
      public Builder setMail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mail = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMail() {
        
        mail_ = getDefaultInstance().getMail();
        onChanged();
        return this;
      }
      /**
       * <code>string mail = 1;</code>
       * @param value The bytes for mail to set.
       * @return This builder for chaining.
       */
      public Builder setMailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mail_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hash_ = "";
      /**
       * <code>string hash = 2;</code>
       * @return The hash.
       */
      public java.lang.String getHash() {
        java.lang.Object ref = hash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hash = 2;</code>
       * @return The bytes for hash.
       */
      public com.google.protobuf.ByteString
          getHashBytes() {
        java.lang.Object ref = hash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hash = 2;</code>
       * @param value The hash to set.
       * @return This builder for chaining.
       */
      public Builder setHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hash = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHash() {
        
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      /**
       * <code>string hash = 2;</code>
       * @param value The bytes for hash to set.
       * @return This builder for chaining.
       */
      public Builder setHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hash_ = value;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <code>.MsgState state = 3;</code>
       * @return The enum numeric value on the wire for state.
       */
      @java.lang.Override public int getStateValue() {
        return state_;
      }
      /**
       * <code>.MsgState state = 3;</code>
       * @param value The enum numeric value on the wire for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateValue(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MsgState state = 3;</code>
       * @return The state.
       */
      @java.lang.Override
      public com.server.Protobufs.LoginMessages.MsgState getState() {
        @SuppressWarnings("deprecation")
        com.server.Protobufs.LoginMessages.MsgState result = com.server.Protobufs.LoginMessages.MsgState.valueOf(state_);
        return result == null ? com.server.Protobufs.LoginMessages.MsgState.UNRECOGNIZED : result;
      }
      /**
       * <code>.MsgState state = 3;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(com.server.Protobufs.LoginMessages.MsgState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MsgState state = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Login)
    }

    // @@protoc_insertion_point(class_scope:Login)
    private static final com.server.Protobufs.LoginMessages.Login DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.server.Protobufs.LoginMessages.Login();
    }

    public static com.server.Protobufs.LoginMessages.Login getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Login>
        PARSER = new com.google.protobuf.AbstractParser<Login>() {
      @java.lang.Override
      public Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Login(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Login> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Login> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.server.Protobufs.LoginMessages.Login getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RegistrationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Registration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string login = 1;</code>
     * @return The login.
     */
    java.lang.String getLogin();
    /**
     * <code>string login = 1;</code>
     * @return The bytes for login.
     */
    com.google.protobuf.ByteString
        getLoginBytes();

    /**
     * <code>string hash = 2;</code>
     * @return The hash.
     */
    java.lang.String getHash();
    /**
     * <code>string hash = 2;</code>
     * @return The bytes for hash.
     */
    com.google.protobuf.ByteString
        getHashBytes();

    /**
     * <code>string mail = 3;</code>
     * @return The mail.
     */
    java.lang.String getMail();
    /**
     * <code>string mail = 3;</code>
     * @return The bytes for mail.
     */
    com.google.protobuf.ByteString
        getMailBytes();

    /**
     * <code>.MsgState state = 4;</code>
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();
    /**
     * <code>.MsgState state = 4;</code>
     * @return The state.
     */
    com.server.Protobufs.LoginMessages.MsgState getState();
  }
  /**
   * Protobuf type {@code Registration}
   */
  public static final class Registration extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Registration)
      RegistrationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Registration.newBuilder() to construct.
    private Registration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Registration() {
      login_ = "";
      hash_ = "";
      mail_ = "";
      state_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Registration();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Registration(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              login_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              hash_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              mail_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.Protobufs.LoginMessages.internal_static_Registration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.Protobufs.LoginMessages.internal_static_Registration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.Protobufs.LoginMessages.Registration.class, com.server.Protobufs.LoginMessages.Registration.Builder.class);
    }

    public static final int LOGIN_FIELD_NUMBER = 1;
    private volatile java.lang.Object login_;
    /**
     * <code>string login = 1;</code>
     * @return The login.
     */
    @java.lang.Override
    public java.lang.String getLogin() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        login_ = s;
        return s;
      }
    }
    /**
     * <code>string login = 1;</code>
     * @return The bytes for login.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HASH_FIELD_NUMBER = 2;
    private volatile java.lang.Object hash_;
    /**
     * <code>string hash = 2;</code>
     * @return The hash.
     */
    @java.lang.Override
    public java.lang.String getHash() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hash_ = s;
        return s;
      }
    }
    /**
     * <code>string hash = 2;</code>
     * @return The bytes for hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHashBytes() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object mail_;
    /**
     * <code>string mail = 3;</code>
     * @return The mail.
     */
    @java.lang.Override
    public java.lang.String getMail() {
      java.lang.Object ref = mail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mail_ = s;
        return s;
      }
    }
    /**
     * <code>string mail = 3;</code>
     * @return The bytes for mail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMailBytes() {
      java.lang.Object ref = mail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private int state_;
    /**
     * <code>.MsgState state = 4;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.MsgState state = 4;</code>
     * @return The state.
     */
    @java.lang.Override public com.server.Protobufs.LoginMessages.MsgState getState() {
      @SuppressWarnings("deprecation")
      com.server.Protobufs.LoginMessages.MsgState result = com.server.Protobufs.LoginMessages.MsgState.valueOf(state_);
      return result == null ? com.server.Protobufs.LoginMessages.MsgState.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(login_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, login_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hash_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hash_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mail_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mail_);
      }
      if (state_ != com.server.Protobufs.LoginMessages.MsgState.MS_ERROR.getNumber()) {
        output.writeEnum(4, state_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(login_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, login_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hash_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hash_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mail_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mail_);
      }
      if (state_ != com.server.Protobufs.LoginMessages.MsgState.MS_ERROR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.server.Protobufs.LoginMessages.Registration)) {
        return super.equals(obj);
      }
      com.server.Protobufs.LoginMessages.Registration other = (com.server.Protobufs.LoginMessages.Registration) obj;

      if (!getLogin()
          .equals(other.getLogin())) return false;
      if (!getHash()
          .equals(other.getHash())) return false;
      if (!getMail()
          .equals(other.getMail())) return false;
      if (state_ != other.state_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOGIN_FIELD_NUMBER;
      hash = (53 * hash) + getLogin().hashCode();
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
      hash = (37 * hash) + MAIL_FIELD_NUMBER;
      hash = (53 * hash) + getMail().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.server.Protobufs.LoginMessages.Registration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.Protobufs.LoginMessages.Registration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.Registration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.Protobufs.LoginMessages.Registration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.Registration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.Protobufs.LoginMessages.Registration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.Registration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.server.Protobufs.LoginMessages.Registration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.Registration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.server.Protobufs.LoginMessages.Registration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.server.Protobufs.LoginMessages.Registration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.server.Protobufs.LoginMessages.Registration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.server.Protobufs.LoginMessages.Registration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Registration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Registration)
        com.server.Protobufs.LoginMessages.RegistrationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.Protobufs.LoginMessages.internal_static_Registration_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.Protobufs.LoginMessages.internal_static_Registration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.Protobufs.LoginMessages.Registration.class, com.server.Protobufs.LoginMessages.Registration.Builder.class);
      }

      // Construct using com.server.Protobufs.LoginMessages.Registration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        login_ = "";

        hash_ = "";

        mail_ = "";

        state_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.server.Protobufs.LoginMessages.internal_static_Registration_descriptor;
      }

      @java.lang.Override
      public com.server.Protobufs.LoginMessages.Registration getDefaultInstanceForType() {
        return com.server.Protobufs.LoginMessages.Registration.getDefaultInstance();
      }

      @java.lang.Override
      public com.server.Protobufs.LoginMessages.Registration build() {
        com.server.Protobufs.LoginMessages.Registration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.server.Protobufs.LoginMessages.Registration buildPartial() {
        com.server.Protobufs.LoginMessages.Registration result = new com.server.Protobufs.LoginMessages.Registration(this);
        result.login_ = login_;
        result.hash_ = hash_;
        result.mail_ = mail_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.server.Protobufs.LoginMessages.Registration) {
          return mergeFrom((com.server.Protobufs.LoginMessages.Registration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.server.Protobufs.LoginMessages.Registration other) {
        if (other == com.server.Protobufs.LoginMessages.Registration.getDefaultInstance()) return this;
        if (!other.getLogin().isEmpty()) {
          login_ = other.login_;
          onChanged();
        }
        if (!other.getHash().isEmpty()) {
          hash_ = other.hash_;
          onChanged();
        }
        if (!other.getMail().isEmpty()) {
          mail_ = other.mail_;
          onChanged();
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.server.Protobufs.LoginMessages.Registration parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.server.Protobufs.LoginMessages.Registration) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object login_ = "";
      /**
       * <code>string login = 1;</code>
       * @return The login.
       */
      public java.lang.String getLogin() {
        java.lang.Object ref = login_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          login_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string login = 1;</code>
       * @return The bytes for login.
       */
      public com.google.protobuf.ByteString
          getLoginBytes() {
        java.lang.Object ref = login_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          login_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string login = 1;</code>
       * @param value The login to set.
       * @return This builder for chaining.
       */
      public Builder setLogin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        login_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string login = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogin() {
        
        login_ = getDefaultInstance().getLogin();
        onChanged();
        return this;
      }
      /**
       * <code>string login = 1;</code>
       * @param value The bytes for login to set.
       * @return This builder for chaining.
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        login_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hash_ = "";
      /**
       * <code>string hash = 2;</code>
       * @return The hash.
       */
      public java.lang.String getHash() {
        java.lang.Object ref = hash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hash = 2;</code>
       * @return The bytes for hash.
       */
      public com.google.protobuf.ByteString
          getHashBytes() {
        java.lang.Object ref = hash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hash = 2;</code>
       * @param value The hash to set.
       * @return This builder for chaining.
       */
      public Builder setHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hash = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHash() {
        
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      /**
       * <code>string hash = 2;</code>
       * @param value The bytes for hash to set.
       * @return This builder for chaining.
       */
      public Builder setHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hash_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mail_ = "";
      /**
       * <code>string mail = 3;</code>
       * @return The mail.
       */
      public java.lang.String getMail() {
        java.lang.Object ref = mail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mail = 3;</code>
       * @return The bytes for mail.
       */
      public com.google.protobuf.ByteString
          getMailBytes() {
        java.lang.Object ref = mail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mail = 3;</code>
       * @param value The mail to set.
       * @return This builder for chaining.
       */
      public Builder setMail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mail = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMail() {
        
        mail_ = getDefaultInstance().getMail();
        onChanged();
        return this;
      }
      /**
       * <code>string mail = 3;</code>
       * @param value The bytes for mail to set.
       * @return This builder for chaining.
       */
      public Builder setMailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mail_ = value;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <code>.MsgState state = 4;</code>
       * @return The enum numeric value on the wire for state.
       */
      @java.lang.Override public int getStateValue() {
        return state_;
      }
      /**
       * <code>.MsgState state = 4;</code>
       * @param value The enum numeric value on the wire for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateValue(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MsgState state = 4;</code>
       * @return The state.
       */
      @java.lang.Override
      public com.server.Protobufs.LoginMessages.MsgState getState() {
        @SuppressWarnings("deprecation")
        com.server.Protobufs.LoginMessages.MsgState result = com.server.Protobufs.LoginMessages.MsgState.valueOf(state_);
        return result == null ? com.server.Protobufs.LoginMessages.MsgState.UNRECOGNIZED : result;
      }
      /**
       * <code>.MsgState state = 4;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(com.server.Protobufs.LoginMessages.MsgState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MsgState state = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Registration)
    }

    // @@protoc_insertion_point(class_scope:Registration)
    private static final com.server.Protobufs.LoginMessages.Registration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.server.Protobufs.LoginMessages.Registration();
    }

    public static com.server.Protobufs.LoginMessages.Registration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Registration>
        PARSER = new com.google.protobuf.AbstractParser<Registration>() {
      @java.lang.Override
      public Registration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Registration(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Registration> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Registration> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.server.Protobufs.LoginMessages.Registration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckRegParameterStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckRegParameterStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Login_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Login_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Registration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Registration_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023LoginMessages.proto\"m\n\027CheckRegParamet" +
      "erStatus\022\017\n\005login\030\001 \001(\tH\000\022\016\n\004mail\030\002 \001(\tH" +
      "\000\022\025\n\013loginStatus\030\003 \001(\010H\000\022\024\n\nmailStatus\030\004" +
      " \001(\010H\000B\004\n\002v1\"=\n\005Login\022\014\n\004mail\030\001 \001(\t\022\014\n\004h" +
      "ash\030\002 \001(\t\022\030\n\005state\030\003 \001(\0162\t.MsgState\"S\n\014R" +
      "egistration\022\r\n\005login\030\001 \001(\t\022\014\n\004hash\030\002 \001(\t" +
      "\022\014\n\004mail\030\003 \001(\t\022\030\n\005state\030\004 \001(\0162\t.MsgState" +
      "*8\n\010MsgState\022\014\n\010MS_ERROR\020\000\022\013\n\007MS_INIT\020\001\022" +
      "\021\n\rMS_SUCCESSFUL\020\002B%\n\024com.server.Protobu" +
      "fsB\rLoginMessagesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CheckRegParameterStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CheckRegParameterStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckRegParameterStatus_descriptor,
        new java.lang.String[] { "Login", "Mail", "LoginStatus", "MailStatus", "V1", });
    internal_static_Login_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Login_descriptor,
        new java.lang.String[] { "Mail", "Hash", "State", });
    internal_static_Registration_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Registration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Registration_descriptor,
        new java.lang.String[] { "Login", "Hash", "Mail", "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
